/****** Object:  Table [dbo].[AscStatementDataGuMonthly]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AscStatementDataGuMonthly](
	[AscStatementData_Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[AscStatementData_Year] [int] NOT NULL,
	[AscStatementData_Month] [int] NOT NULL,
	[AscStatementData_GenerationUnit_Id] [decimal](18, 0) NOT NULL,
	[AscStatementData_Generator_Id] [decimal](18, 0) NOT NULL,
	[AscStatementData_TechnologyType_Code] [varchar](4) NULL,
	[AscStatementData_FuelType_Code] [varchar](4) NULL,
	[AscStatementData_UnitNumber] [varchar](10) NULL,
	[AscStatementData_InstalledCapacity_KW] [int] NULL,
	[AscStatementData_location] [varchar](50) NULL,
	[AscStatementData_IsDisabled] [bit] NULL,
	[AscStatementData_EffectiveFrom] [datetime] NULL,
	[AscStatementData_EffectiveTo] [datetime] NULL,
	[AscStatementData_ModifiedBy] [decimal](18, 0) NULL,
	[AscStatementData_ModifiedOn] [datetime] NULL,
	[AscStatementData_UnitName] [varchar](100) NULL,
	[AscStatementData_SOUnitId] [int] NOT NULL,
	[AscStatementData_IsEnergyImported] [bit] NULL,
	[AscStatementData_PartyRegisteration_Id] [int] NOT NULL,
	[AscStatementData_PartyRegisteration_Name] [nvarchar](200) NULL,
	[AscStatementData_PartyCategory_Code] [nvarchar](50) NULL,
	[AscStatementData_PartyType_Code] [nvarchar](50) NULL,
	[AscStatementData_Congestion_Zone] [nvarchar](50) NULL,
	[AscStatementData_SO_MP] [decimal](25, 13) NULL,
	[AscStatementData_SO_AC] [decimal](25, 13) NULL,
	[AscStatementData_SO_AC_ASC] [decimal](25, 13) NULL,
	[AscStatementData_SO_MR_EP] [decimal](25, 13) NULL,
	[AscStatementData_SO_MR_VC] [decimal](25, 13) NULL,
	[AscStatementData_SO_RG_VC] [decimal](25, 13) NULL,
	[AscStatementData_SO_RG_EG_ARE] [decimal](25, 13) NULL,
	[AscStatementData_SO_IG_VC] [decimal](25, 13) NULL,
	[AscStatementData_SO_IG_EPG] [decimal](25, 13) NULL,
	[AscStatementData_MR_EAG] [decimal](25, 13) NULL,
	[AscStatementData_MR_EPG] [decimal](25, 13) NULL,
	[AscStatementData_MRC] [decimal](25, 13) NULL,
	[AscStatementData_RG_EAG] [decimal](25, 13) NULL,
	[AscStatementData_AC_MOD] [decimal](25, 13) NULL,
	[AscStatementData_RG_LOCC] [decimal](25, 13) NULL,
	[AscStatementData_IG_EAG] [decimal](25, 13) NULL,
	[AscStatementData_IG_EPG] [decimal](25, 13) NULL,
	[AscStatementData_IG_UPC] [decimal](25, 13) NULL,
	[AscStatementData_AC_Total] [decimal](25, 13) NULL,
	[AscStatementData_MtPartyCategory_Id] [decimal](18, 0) NULL,
	[AscStatementData_TaxZoneID] [int] NULL,
	[AscStatementData_CongestedZoneID] [int] NULL,
	[AscStatementData_SO_RG_UT] [varchar](100) NULL,
	[AscStatementData_SC_BSC] [decimal](25, 13) NULL,
	[AscStatementData_MAC] [decimal](25, 13) NULL,
	[AscStatementData_GBS_BSC] [decimal](25, 13) NULL,
	[AscStatementData_GS_NS] [int] NULL,
	[AscStatementData_GS_SC] [decimal](25, 13) NULL,
	[AscStatementData_IsIG] [bit] NULL,
	[AscStatementData_IsRG] [bit] NULL,
	[AscStatementData_IsGenMR] [bit] NULL,
	[AscStatementData_IsGenBS] [bit] NULL,
	[AscStatementData_IsGenS] [bit] NULL,
	[AscStatementData_RG_AC] [decimal](25, 13) NULL,
	[AscStatementData_IG_AC] [decimal](25, 13) NULL,
	[AscStatementData_MR_UPC] [decimal](25, 13) NULL,
	[AscStatementData_StatementProcessId] [decimal](18, 0) NOT NULL,
	[AscStatementData_CongestedZone] [nvarchar](50) NULL,
 CONSTRAINT [PK_AscStatementDataGuMonthly] PRIMARY KEY CLUSTERED 
(
	[AscStatementData_Year] ASC,
	[AscStatementData_Month] ASC,
	[AscStatementData_SOUnitId] ASC,
	[AscStatementData_PartyRegisteration_Id] ASC,
	[AscStatementData_StatementProcessId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
