/****** Object:  Table [dbo].[AscStatementDataZoneMonthly_SettlementProcess]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.AscStatementDataZoneMonthly_SettlementProcess(
	[AscStatementData_Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[AscStatementData_Year] [int] NOT NULL,
	[AscStatementData_Month] [int] NOT NULL,
	[AscStatementData_Congestion_Zone] [nvarchar](50) NULL,
	[AscStatementData_SO_MP] [decimal](28, 13) NULL,
	[AscStatementData_SO_AC] [decimal](28, 13) NULL,
	[AscStatementData_SO_AC_ASC] [decimal](28, 13) NULL,
	[AscStatementData_SO_MR_EP] [decimal](28, 13) NULL,
	[AscStatementData_SO_MR_VC] [decimal](28, 13) NULL,
	[AscStatementData_SO_RG_VC] [decimal](28, 13) NULL,
	[AscStatementData_SO_RG_EG_ARE] [decimal](28, 13) NULL,
	[AscStatementData_SO_IG_VC] [decimal](28, 13) NULL,
	[AscStatementData_SO_IG_EPG] [decimal](28, 13) NULL,
	[AscStatementData_MR_EAG] [decimal](28, 13) NULL,
	[AscStatementData_MR_EPG] [decimal](28, 13) NULL,
	[AscStatementData_MRC] [decimal](28, 13) NULL,
	[AscStatementData_RG_EAG] [decimal](28, 13) NULL,
	[AscStatementData_AC_MOD] [decimal](28, 13) NULL,
	[AscStatementData_RG_LOCC] [decimal](28, 13) NULL,
	[AscStatementData_IG_EAG] [decimal](28, 13) NULL,
	[AscStatementData_IG_EPG] [decimal](28, 13) NULL,
	[AscStatementData_IG_UPC] [decimal](28, 13) NULL,
	[AscStatementData_AC_Total] [decimal](28, 13) NULL,
	[AscStatementData_TaxZoneID] [int] NULL,
	[AscStatementData_CongestedZoneID] [int] NULL,
	[AscStatementData_SC_BSC] [decimal](28, 13) NULL,
	[AscStatementData_MAC] [decimal](28, 13) NULL,
	[AscStatementData_TAC] [decimal](28, 13) NULL,
	[AscStatementData_TD] [decimal](28, 13) NULL,
	[AscStatementData_GS_SC] [decimal](28, 13) NULL,
	[AscStatementData_GBS_BSC] [decimal](28, 13) NULL,
	[AscStatementData_RG_AC] [decimal](28, 13) NULL,
	[AscStatementData_IG_AC] [decimal](28, 13) NULL,
	[AscStatementData_StatementProcessId] [decimal](18, 0) NULL,
	[AscStatementData_SettlementProcessId] [decimal](18, 0) NULL,
	[AscStatementData_KE_ES] [decimal](28, 13) NULL,
	[AscStatementData_TP] [decimal](28, 13) NULL,
	[AscStatementData_ES_BS] [decimal](28, 13) NULL,
	[AscStatementData_CongestedZone] [nvarchar](50) NULL,
	[AscStatementData_TR] [decimal](25, 13) NULL,
	[AscStatementData_KE_EB] [decimal](25, 13) NULL
) ON [PRIMARY]
