/****** Object:  Table [dbo].[BmeStatementDataMpCategoryHourly_SettlementProcess]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.BmeStatementDataMpCategoryHourly_SettlementProcess(
	[BmeStatementData_Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[BmeStatementData_NtdcDateTime] [datetime] NULL,
	[BmeStatementData_Year] [int] NOT NULL,
	[BmeStatementData_Month] [int] NOT NULL,
	[BmeStatementData_Day] [int] NOT NULL,
	[BmeStatementData_Hour] [int] NOT NULL,
	[BmeStatementData_AdjustedEnergy] [decimal](18, 0) NULL,
	[BmeStatementData_TransmissionLosses] [decimal](25, 13) NULL,
	[BmeStatementData_DemandedEnergy] [decimal](25, 13) NULL,
	[BmeStatementData_UpliftTransmissionLosses] [decimal](25, 13) NULL,
	[BmeStatementData_ActualEnergy] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedActual] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedGenerated] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedImport] [decimal](25, 13) NULL,
	[BmeStatementData_PartyRegisteration_Id] [decimal](18, 0) NULL,
	[BmeStatementData_PartyName] [nvarchar](200) NULL,
	[BmeStatementData_PartyType_Code] [varchar](4) NULL,
	[BmeStatementData_PartyCategory_Code] [varchar](4) NULL,
	[BmeStatementData_AdjustedEnergyImport] [decimal](25, 13) NULL,
	[BmeStatementData_AdjustedEnergyExport] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedGeneratedLegacy] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedImportedLegacy] [decimal](25, 13) NULL,
	[BmeStatementData_CAPLegacy] [decimal](25, 13) NULL,
	[BmeStatementData_EnergySuppliedImported] [decimal](25, 13) NULL,
	[BmeStatementData_ActualCapacity] [decimal](25, 13) NULL,
	[BmeStatementData_EnergyTradedBought] [decimal](25, 13) NULL,
	[BmeStatementData_EnergyTradedSold] [decimal](25, 13) NULL,
	[BmeStatementData_EnergyTraded] [decimal](25, 13) NULL,
	[BmeStatementData_Imbalance] [decimal](25, 13) NULL,
	[BmeStatementData_ImbalanceCharges] [decimal](25, 13) NULL,
	[BmeStatementData_MarginalPrice] [decimal](25, 13) NULL,
	[BmeStatementData_BSUPRatioPP] [decimal](25, 13) NULL,
	[BmeStatementData_IsPowerPool] [bit] NULL,
	[BmeStatementData_CongestedZoneID] [int] NULL,
	[BmeStatementData_ES] [decimal](25, 13) NULL,
	[BmeStatementData_MAC] [decimal](25, 13) NULL,
	[BmeStatementData_IG_AC] [decimal](25, 13) NULL,
	[BmeStatementData_RG_AC] [decimal](25, 13) NULL,
	[BmeStatementData_GS_SC] [decimal](25, 13) NULL,
	[BmeStatementData_GBS_BSC] [decimal](25, 13) NULL,
	[BmeStatementData_TAC] [decimal](25, 13) NULL,
	[BmeStatementData_MRC] [decimal](25, 13) NULL,
	[BmeStatementData_TC] [decimal](25, 13) NULL,
	[BmeStatementData_StatementProcessId] [decimal](18, 0) NULL,
	[BmeStatementData_SettlementProcessId] [decimal](18, 0) NULL,
	[BmeStatementData_CongestedZone] [nvarchar](50) NULL,
	[BmeStatementData_ActualEnergy_Metered] [decimal](25, 13) NULL
) ON [PRIMARY]
